//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int Priority { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Video { get; set; }
        public Nullable<int> TotalShow { get; set; }
    
        public virtual Priority Priority1 { get; set; }
        public virtual Company Company { get; set; }
    }
}
